// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmessage.proto

package com.appjishu.fpush.core.proto;

/**
 * Protobuf type {@code com.appjishu.fpush.core.proto.FBody}
 */
public  final class FBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.appjishu.fpush.core.proto.FBody)
    FBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FBody.newBuilder() to construct.
  private FBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FBody() {
    collapseKey_ = "";
    payload_ = "";
    title_ = "";
    description_ = "";
    notifyType_ = 0;
    timeToLive_ = 0L;
    passThrough_ = 0;
    notifyId_ = 0;
    restrictedPackageNames_ = "";
    extra_ = "";
    apsProperFields_ = "";
    timeToSend_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            collapseKey_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            payload_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 40: {

            notifyType_ = input.readInt32();
            break;
          }
          case 48: {

            timeToLive_ = input.readInt64();
            break;
          }
          case 56: {

            passThrough_ = input.readInt32();
            break;
          }
          case 64: {

            notifyId_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            restrictedPackageNames_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            apsProperFields_ = s;
            break;
          }
          case 96: {

            timeToSend_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.appjishu.fpush.core.proto.FMessageCollection.internal_static_com_appjishu_fpush_core_proto_FBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.appjishu.fpush.core.proto.FMessageCollection.internal_static_com_appjishu_fpush_core_proto_FBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.appjishu.fpush.core.proto.FBody.class, com.appjishu.fpush.core.proto.FBody.Builder.class);
  }

  public static final int COLLAPSEKEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object collapseKey_;
  /**
   * <code>string collapseKey = 1;</code>
   */
  public java.lang.String getCollapseKey() {
    java.lang.Object ref = collapseKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collapseKey_ = s;
      return s;
    }
  }
  /**
   * <code>string collapseKey = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCollapseKeyBytes() {
    java.lang.Object ref = collapseKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collapseKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private volatile java.lang.Object payload_;
  /**
   * <code>string payload = 2;</code>
   */
  public java.lang.String getPayload() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payload_ = s;
      return s;
    }
  }
  /**
   * <code>string payload = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 3;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 4;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFYTYPE_FIELD_NUMBER = 5;
  private int notifyType_;
  /**
   * <code>int32 notifyType = 5;</code>
   */
  public int getNotifyType() {
    return notifyType_;
  }

  public static final int TIMETOLIVE_FIELD_NUMBER = 6;
  private long timeToLive_;
  /**
   * <code>int64 timeToLive = 6;</code>
   */
  public long getTimeToLive() {
    return timeToLive_;
  }

  public static final int PASSTHROUGH_FIELD_NUMBER = 7;
  private int passThrough_;
  /**
   * <code>int32 passThrough = 7;</code>
   */
  public int getPassThrough() {
    return passThrough_;
  }

  public static final int NOTIFYID_FIELD_NUMBER = 8;
  private int notifyId_;
  /**
   * <code>int32 notifyId = 8;</code>
   */
  public int getNotifyId() {
    return notifyId_;
  }

  public static final int RESTRICTEDPACKAGENAMES_FIELD_NUMBER = 9;
  private volatile java.lang.Object restrictedPackageNames_;
  /**
   * <code>string restrictedPackageNames = 9;</code>
   */
  public java.lang.String getRestrictedPackageNames() {
    java.lang.Object ref = restrictedPackageNames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      restrictedPackageNames_ = s;
      return s;
    }
  }
  /**
   * <code>string restrictedPackageNames = 9;</code>
   */
  public com.google.protobuf.ByteString
      getRestrictedPackageNamesBytes() {
    java.lang.Object ref = restrictedPackageNames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      restrictedPackageNames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRA_FIELD_NUMBER = 10;
  private volatile java.lang.Object extra_;
  /**
   * <code>string extra = 10;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <code>string extra = 10;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APSPROPERFIELDS_FIELD_NUMBER = 11;
  private volatile java.lang.Object apsProperFields_;
  /**
   * <code>string apsProperFields = 11;</code>
   */
  public java.lang.String getApsProperFields() {
    java.lang.Object ref = apsProperFields_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apsProperFields_ = s;
      return s;
    }
  }
  /**
   * <code>string apsProperFields = 11;</code>
   */
  public com.google.protobuf.ByteString
      getApsProperFieldsBytes() {
    java.lang.Object ref = apsProperFields_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apsProperFields_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMETOSEND_FIELD_NUMBER = 12;
  private long timeToSend_;
  /**
   * <code>int64 timeToSend = 12;</code>
   */
  public long getTimeToSend() {
    return timeToSend_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCollapseKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, collapseKey_);
    }
    if (!getPayloadBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, payload_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (notifyType_ != 0) {
      output.writeInt32(5, notifyType_);
    }
    if (timeToLive_ != 0L) {
      output.writeInt64(6, timeToLive_);
    }
    if (passThrough_ != 0) {
      output.writeInt32(7, passThrough_);
    }
    if (notifyId_ != 0) {
      output.writeInt32(8, notifyId_);
    }
    if (!getRestrictedPackageNamesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, restrictedPackageNames_);
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, extra_);
    }
    if (!getApsProperFieldsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, apsProperFields_);
    }
    if (timeToSend_ != 0L) {
      output.writeInt64(12, timeToSend_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCollapseKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, collapseKey_);
    }
    if (!getPayloadBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, payload_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (notifyType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, notifyType_);
    }
    if (timeToLive_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timeToLive_);
    }
    if (passThrough_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, passThrough_);
    }
    if (notifyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, notifyId_);
    }
    if (!getRestrictedPackageNamesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, restrictedPackageNames_);
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, extra_);
    }
    if (!getApsProperFieldsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, apsProperFields_);
    }
    if (timeToSend_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, timeToSend_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.appjishu.fpush.core.proto.FBody)) {
      return super.equals(obj);
    }
    com.appjishu.fpush.core.proto.FBody other = (com.appjishu.fpush.core.proto.FBody) obj;

    boolean result = true;
    result = result && getCollapseKey()
        .equals(other.getCollapseKey());
    result = result && getPayload()
        .equals(other.getPayload());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && (getNotifyType()
        == other.getNotifyType());
    result = result && (getTimeToLive()
        == other.getTimeToLive());
    result = result && (getPassThrough()
        == other.getPassThrough());
    result = result && (getNotifyId()
        == other.getNotifyId());
    result = result && getRestrictedPackageNames()
        .equals(other.getRestrictedPackageNames());
    result = result && getExtra()
        .equals(other.getExtra());
    result = result && getApsProperFields()
        .equals(other.getApsProperFields());
    result = result && (getTimeToSend()
        == other.getTimeToSend());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLLAPSEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getCollapseKey().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + NOTIFYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNotifyType();
    hash = (37 * hash) + TIMETOLIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeToLive());
    hash = (37 * hash) + PASSTHROUGH_FIELD_NUMBER;
    hash = (53 * hash) + getPassThrough();
    hash = (37 * hash) + NOTIFYID_FIELD_NUMBER;
    hash = (53 * hash) + getNotifyId();
    hash = (37 * hash) + RESTRICTEDPACKAGENAMES_FIELD_NUMBER;
    hash = (53 * hash) + getRestrictedPackageNames().hashCode();
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + APSPROPERFIELDS_FIELD_NUMBER;
    hash = (53 * hash) + getApsProperFields().hashCode();
    hash = (37 * hash) + TIMETOSEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeToSend());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appjishu.fpush.core.proto.FBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.appjishu.fpush.core.proto.FBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appjishu.fpush.core.proto.FBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.appjishu.fpush.core.proto.FBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.appjishu.fpush.core.proto.FBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.appjishu.fpush.core.proto.FBody)
      com.appjishu.fpush.core.proto.FBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appjishu.fpush.core.proto.FMessageCollection.internal_static_com_appjishu_fpush_core_proto_FBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appjishu.fpush.core.proto.FMessageCollection.internal_static_com_appjishu_fpush_core_proto_FBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appjishu.fpush.core.proto.FBody.class, com.appjishu.fpush.core.proto.FBody.Builder.class);
    }

    // Construct using com.appjishu.fpush.core.proto.FBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      collapseKey_ = "";

      payload_ = "";

      title_ = "";

      description_ = "";

      notifyType_ = 0;

      timeToLive_ = 0L;

      passThrough_ = 0;

      notifyId_ = 0;

      restrictedPackageNames_ = "";

      extra_ = "";

      apsProperFields_ = "";

      timeToSend_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.appjishu.fpush.core.proto.FMessageCollection.internal_static_com_appjishu_fpush_core_proto_FBody_descriptor;
    }

    @java.lang.Override
    public com.appjishu.fpush.core.proto.FBody getDefaultInstanceForType() {
      return com.appjishu.fpush.core.proto.FBody.getDefaultInstance();
    }

    @java.lang.Override
    public com.appjishu.fpush.core.proto.FBody build() {
      com.appjishu.fpush.core.proto.FBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.appjishu.fpush.core.proto.FBody buildPartial() {
      com.appjishu.fpush.core.proto.FBody result = new com.appjishu.fpush.core.proto.FBody(this);
      result.collapseKey_ = collapseKey_;
      result.payload_ = payload_;
      result.title_ = title_;
      result.description_ = description_;
      result.notifyType_ = notifyType_;
      result.timeToLive_ = timeToLive_;
      result.passThrough_ = passThrough_;
      result.notifyId_ = notifyId_;
      result.restrictedPackageNames_ = restrictedPackageNames_;
      result.extra_ = extra_;
      result.apsProperFields_ = apsProperFields_;
      result.timeToSend_ = timeToSend_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.appjishu.fpush.core.proto.FBody) {
        return mergeFrom((com.appjishu.fpush.core.proto.FBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.appjishu.fpush.core.proto.FBody other) {
      if (other == com.appjishu.fpush.core.proto.FBody.getDefaultInstance()) return this;
      if (!other.getCollapseKey().isEmpty()) {
        collapseKey_ = other.collapseKey_;
        onChanged();
      }
      if (!other.getPayload().isEmpty()) {
        payload_ = other.payload_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getNotifyType() != 0) {
        setNotifyType(other.getNotifyType());
      }
      if (other.getTimeToLive() != 0L) {
        setTimeToLive(other.getTimeToLive());
      }
      if (other.getPassThrough() != 0) {
        setPassThrough(other.getPassThrough());
      }
      if (other.getNotifyId() != 0) {
        setNotifyId(other.getNotifyId());
      }
      if (!other.getRestrictedPackageNames().isEmpty()) {
        restrictedPackageNames_ = other.restrictedPackageNames_;
        onChanged();
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      if (!other.getApsProperFields().isEmpty()) {
        apsProperFields_ = other.apsProperFields_;
        onChanged();
      }
      if (other.getTimeToSend() != 0L) {
        setTimeToSend(other.getTimeToSend());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.appjishu.fpush.core.proto.FBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.appjishu.fpush.core.proto.FBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object collapseKey_ = "";
    /**
     * <code>string collapseKey = 1;</code>
     */
    public java.lang.String getCollapseKey() {
      java.lang.Object ref = collapseKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collapseKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string collapseKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCollapseKeyBytes() {
      java.lang.Object ref = collapseKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collapseKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string collapseKey = 1;</code>
     */
    public Builder setCollapseKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collapseKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string collapseKey = 1;</code>
     */
    public Builder clearCollapseKey() {
      
      collapseKey_ = getDefaultInstance().getCollapseKey();
      onChanged();
      return this;
    }
    /**
     * <code>string collapseKey = 1;</code>
     */
    public Builder setCollapseKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collapseKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object payload_ = "";
    /**
     * <code>string payload = 2;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string payload = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payload = 2;</code>
     */
    public Builder setPayload(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 2;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 2;</code>
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      payload_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int notifyType_ ;
    /**
     * <code>int32 notifyType = 5;</code>
     */
    public int getNotifyType() {
      return notifyType_;
    }
    /**
     * <code>int32 notifyType = 5;</code>
     */
    public Builder setNotifyType(int value) {
      
      notifyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 notifyType = 5;</code>
     */
    public Builder clearNotifyType() {
      
      notifyType_ = 0;
      onChanged();
      return this;
    }

    private long timeToLive_ ;
    /**
     * <code>int64 timeToLive = 6;</code>
     */
    public long getTimeToLive() {
      return timeToLive_;
    }
    /**
     * <code>int64 timeToLive = 6;</code>
     */
    public Builder setTimeToLive(long value) {
      
      timeToLive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeToLive = 6;</code>
     */
    public Builder clearTimeToLive() {
      
      timeToLive_ = 0L;
      onChanged();
      return this;
    }

    private int passThrough_ ;
    /**
     * <code>int32 passThrough = 7;</code>
     */
    public int getPassThrough() {
      return passThrough_;
    }
    /**
     * <code>int32 passThrough = 7;</code>
     */
    public Builder setPassThrough(int value) {
      
      passThrough_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 passThrough = 7;</code>
     */
    public Builder clearPassThrough() {
      
      passThrough_ = 0;
      onChanged();
      return this;
    }

    private int notifyId_ ;
    /**
     * <code>int32 notifyId = 8;</code>
     */
    public int getNotifyId() {
      return notifyId_;
    }
    /**
     * <code>int32 notifyId = 8;</code>
     */
    public Builder setNotifyId(int value) {
      
      notifyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 notifyId = 8;</code>
     */
    public Builder clearNotifyId() {
      
      notifyId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object restrictedPackageNames_ = "";
    /**
     * <code>string restrictedPackageNames = 9;</code>
     */
    public java.lang.String getRestrictedPackageNames() {
      java.lang.Object ref = restrictedPackageNames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        restrictedPackageNames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string restrictedPackageNames = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRestrictedPackageNamesBytes() {
      java.lang.Object ref = restrictedPackageNames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        restrictedPackageNames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string restrictedPackageNames = 9;</code>
     */
    public Builder setRestrictedPackageNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      restrictedPackageNames_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string restrictedPackageNames = 9;</code>
     */
    public Builder clearRestrictedPackageNames() {
      
      restrictedPackageNames_ = getDefaultInstance().getRestrictedPackageNames();
      onChanged();
      return this;
    }
    /**
     * <code>string restrictedPackageNames = 9;</code>
     */
    public Builder setRestrictedPackageNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      restrictedPackageNames_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <code>string extra = 10;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extra = 10;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra = 10;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 10;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 10;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object apsProperFields_ = "";
    /**
     * <code>string apsProperFields = 11;</code>
     */
    public java.lang.String getApsProperFields() {
      java.lang.Object ref = apsProperFields_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apsProperFields_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string apsProperFields = 11;</code>
     */
    public com.google.protobuf.ByteString
        getApsProperFieldsBytes() {
      java.lang.Object ref = apsProperFields_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apsProperFields_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string apsProperFields = 11;</code>
     */
    public Builder setApsProperFields(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      apsProperFields_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string apsProperFields = 11;</code>
     */
    public Builder clearApsProperFields() {
      
      apsProperFields_ = getDefaultInstance().getApsProperFields();
      onChanged();
      return this;
    }
    /**
     * <code>string apsProperFields = 11;</code>
     */
    public Builder setApsProperFieldsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      apsProperFields_ = value;
      onChanged();
      return this;
    }

    private long timeToSend_ ;
    /**
     * <code>int64 timeToSend = 12;</code>
     */
    public long getTimeToSend() {
      return timeToSend_;
    }
    /**
     * <code>int64 timeToSend = 12;</code>
     */
    public Builder setTimeToSend(long value) {
      
      timeToSend_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeToSend = 12;</code>
     */
    public Builder clearTimeToSend() {
      
      timeToSend_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.appjishu.fpush.core.proto.FBody)
  }

  // @@protoc_insertion_point(class_scope:com.appjishu.fpush.core.proto.FBody)
  private static final com.appjishu.fpush.core.proto.FBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.appjishu.fpush.core.proto.FBody();
  }

  public static com.appjishu.fpush.core.proto.FBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FBody>
      PARSER = new com.google.protobuf.AbstractParser<FBody>() {
    @java.lang.Override
    public FBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.appjishu.fpush.core.proto.FBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

