// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmessage.proto

package com.appjishu.fpush.core.proto;

public interface FHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appjishu.fpush.core.proto.FHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 crcCode = 1;</code>
   */
  int getCrcCode();

  /**
   * <code>int32 length = 2;</code>
   */
  int getLength();

  /**
   * <code>int64 sessionId = 3;</code>
   */
  long getSessionId();

  /**
   * <code>int32 type = 4;</code>
   */
  int getType();

  /**
   * <code>int32 priority = 5;</code>
   */
  int getPriority();
}
