// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmessage.proto

package com.appjishu.fpush.core.proto;

public interface FHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appjishu.fpush.core.proto.FHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();

  /**
   * <code>int32 type = 2;</code>
   */
  int getType();

  /**
   * <code>int32 priority = 3;</code>
   */
  int getPriority();

  /**
   * <code>string regId = 4;</code>
   */
  java.lang.String getRegId();
  /**
   * <code>string regId = 4;</code>
   */
  com.google.protobuf.ByteString
      getRegIdBytes();

  /**
   * <pre>
   **
   * 用别名来标识一个用户。一个设备只能绑定一个别名
   * 推送消息给某个用户，一般用这个用户的应用系统中的userId设置成alias，适用于单用户单设备在线聊天的应用场景
   * </pre>
   *
   * <code>string alias = 5;</code>
   */
  java.lang.String getAlias();
  /**
   * <pre>
   **
   * 用别名来标识一个用户。一个设备只能绑定一个别名
   * 推送消息给某个用户，一般用这个用户的应用系统中的userId设置成alias，适用于单用户单设备在线聊天的应用场景
   * </pre>
   *
   * <code>string alias = 5;</code>
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   **
   * 推送消息给某个用户，一般用这个用户的应用系统中的userId设置成alias，适用于单用户多设备同时在线聊天的应用场景
   * </pre>
   *
   * <code>string account = 6;</code>
   */
  java.lang.String getAccount();
  /**
   * <pre>
   **
   * 推送消息给某个用户，一般用这个用户的应用系统中的userId设置成alias，适用于单用户多设备同时在线聊天的应用场景
   * </pre>
   *
   * <code>string account = 6;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string resultCode = 7;</code>
   */
  java.lang.String getResultCode();
  /**
   * <code>string resultCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getResultCodeBytes();

  /**
   * <code>string resultText = 8;</code>
   */
  java.lang.String getResultText();
  /**
   * <code>string resultText = 8;</code>
   */
  com.google.protobuf.ByteString
      getResultTextBytes();

  /**
   * <code>int64 appId = 9;</code>
   */
  long getAppId();

  /**
   * <code>string clientToken = 10;</code>
   */
  java.lang.String getClientToken();
  /**
   * <code>string clientToken = 10;</code>
   */
  com.google.protobuf.ByteString
      getClientTokenBytes();
}
