// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmessage.proto

package com.appjishu.fpush.core.proto;

public final class FMessageCollection {
  private FMessageCollection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appjishu_fpush_core_proto_FHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appjishu_fpush_core_proto_FHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appjishu_fpush_core_proto_FMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appjishu_fpush_core_proto_FMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016fmessage.proto\022\035com.appjishu.fpush.cor" +
      "e.proto\"]\n\007FHeader\022\017\n\007crcCode\030\001 \001(\005\022\016\n\006l" +
      "ength\030\002 \001(\005\022\021\n\tsessionId\030\003 \001(\003\022\014\n\004type\030\004" +
      " \001(\005\022\020\n\010priority\030\005 \001(\005\"P\n\010FMessage\0226\n\006he" +
      "ader\030\001 \001(\0132&.com.appjishu.fpush.core.pro" +
      "to.FHeader\022\014\n\004body\030\002 \001(\tB5\n\035com.appjishu" +
      ".fpush.core.protoB\022FMessageCollectionP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_appjishu_fpush_core_proto_FHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appjishu_fpush_core_proto_FHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appjishu_fpush_core_proto_FHeader_descriptor,
        new java.lang.String[] { "CrcCode", "Length", "SessionId", "Type", "Priority", });
    internal_static_com_appjishu_fpush_core_proto_FMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appjishu_fpush_core_proto_FMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appjishu_fpush_core_proto_FMessage_descriptor,
        new java.lang.String[] { "Header", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
