// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmessage.proto

package com.appjishu.fpush.core.proto;

public interface FMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appjishu.fpush.core.proto.FMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.appjishu.fpush.core.proto.FHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.com.appjishu.fpush.core.proto.FHeader header = 1;</code>
   */
  com.appjishu.fpush.core.proto.FHeader getHeader();
  /**
   * <code>.com.appjishu.fpush.core.proto.FHeader header = 1;</code>
   */
  com.appjishu.fpush.core.proto.FHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string body = 2;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
